CREATE TABLE AREA_MASTER (
  CODE NCHAR(4) PRIMARY KEY,
  NAME VARCHAR
);

INSERT INTO AREA_MASTER (CODE, NAME) VALUES ( 'SA01','東京都' );
INSERT INTO AREA_MASTER (CODE, NAME) VALUES ( 'SA02','神奈川県' );
INSERT INTO AREA_MASTER (CODE, NAME) VALUES ( 'SA03','埼玉県' );
